build(deps-dev): Bump prettier from 2.8.4 to 2.8.6 (#96)
Bumps [prettier](https://github.com/prettier/prettier) from 2.8.4 to
2.8.6.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/prettier/prettier/releases">prettier's
releases</a>.</em></p>
<blockquote>
<h2>2.8.6</h2>
<ul>
<li>Allow decorators on private members and class expressions</li>
</ul>
<p>🔗 <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#286">Changelog</a></p>
<h2>2.8.5</h2>
<ul>
<li>Support TypeScript 5.0</li>
</ul>
<p>🔗 <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#285">Changelog</a></p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md">prettier's
changelog</a>.</em></p>
<blockquote>
<h1>2.8.6</h1>
<p><a
href="https://github.com/prettier/prettier/compare/2.8.5...2.8.6">diff</a></p>
<h4>Allow decorators on private members and class expressions (<a
href="https://redirect.github.com/prettier/prettier/pull/14548">#14548</a>
by <a href="https://github.com/fisker"><code>@​fisker</code></a>)</h4>
<!-- raw HTML omitted -->
<pre lang="ts"><code>// Input
class A {
  @decorator()
  #privateMethod () {}
}
<p>// Prettier 2.8.5
SyntaxError: Decorators are not valid here. (2:3)
1 | class A {
&gt; 2 | <a
href="https://github.com/decorator"><code>@​decorator</code></a>()
|   ^^^^^^^^^^^^
3 |   #privateMethod () {}
4 | }</p>
<p>// Prettier 2.8.6
class A {
<a href="https://github.com/decorator"><code>@​decorator</code></a>()
#privateMethod() {}
}
</code></pre></p>
<h1>2.8.5</h1>
<p><a
href="https://github.com/prettier/prettier/compare/2.8.4...2.8.5">diff</a></p>
<h4>Support TypeScript 5.0 (<a
href="https://redirect.github.com/prettier/prettier/pull/14391">#14391</a>
by <a href="https://github.com/fisker"><code>@​fisker</code></a>, <a
href="https://redirect.github.com/prettier/prettier/pull/13819">#13819</a>
by <a href="https://github.com/fisker"><code>@​fisker</code></a>, <a
href="https://github.com/sosukesuzuki"><code>@​sosukesuzuki</code></a>)</h4>
<p>TypeScript 5.0 introduces two new syntactic features:</p>
<ul>
<li><code>const</code> modifiers for type parameters</li>
<li><code>export type *</code> declarations</li>
</ul>
<h4>Add missing parentheses for decorator (<a
href="https://redirect.github.com/prettier/prettier/pull/14393">#14393</a>
by <a href="https://github.com/fisker"><code>@​fisker</code></a>)</h4>
<!-- raw HTML omitted -->
<pre lang="jsx"><code>// Input
class Person {
  @(myDecoratorArray[0])
  greet() {}
}
<p>&lt;/tr&gt;&lt;/table&gt;
</code></pre></p>
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/prettier/prettier/commit/10fe1ed6230c6dcdce879104b69cfb2274728c86"><code>10fe1ed</code></a>
Release 2.8.6</li>
<li><a
href="https://github.com/prettier/prettier/commit/44aef0b1ba067cd286ae5b79a9f1f17c751e4cdf"><code>44aef0b</code></a>
Allow decorator on private members and class expressions (<a
href="https://redirect.github.com/prettier/prettier/issues/14548">#14548</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/ddf3b43c33e2e98f6413b5232ad623876d96738e"><code>ddf3b43</code></a>
Clean changelog</li>
<li><a
href="https://github.com/prettier/prettier/commit/71ba29f22bf39d8ddbfd42f33fefd8efdd28a64b"><code>71ba29f</code></a>
Git blame ignore 2.8.5</li>
<li><a
href="https://github.com/prettier/prettier/commit/c1808e86a3c7c2c8f43093f99e78fce3b6d0a97d"><code>c1808e8</code></a>
Bump Prettier dependency to 2.8.5</li>
<li><a
href="https://github.com/prettier/prettier/commit/0a7953591661bc2f54a9124d8ced69c19c1c0353"><code>0a79535</code></a>
Release 2.8.5</li>
<li><a
href="https://github.com/prettier/prettier/commit/019ebe52078efb6ba0ed802ea104617744f42e4c"><code>019ebe5</code></a>
Support TypeScript 5 (backport <a
href="https://redirect.github.com/prettier/prettier/issues/14391">#14391</a>
and <a
href="https://redirect.github.com/prettier/prettier/issues/13819">#13819</a>)
(<a
href="https://redirect.github.com/prettier/prettier/issues/14512">#14512</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/e7b383b570db0f5b792887aa87e7b090f43125cb"><code>e7b383b</code></a>
Support <code>max_line_length=off</code> when parsing
<code>.editorconfig</code> (<a
href="https://redirect.github.com/prettier/prettier/issues/14516">#14516</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/5446a8f32a2717762c4d7a1bd5fe2615d76ebec7"><code>5446a8f</code></a>
Build(deps-dev): Bump webpack from 5.73.0 to 5.76.0 in /website (<a
href="https://redirect.github.com/prettier/prettier/issues/14511">#14511</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/03f0b90cb9d0654348822e46cffcd7121dac17ba"><code>03f0b90</code></a>
Build(deps-dev): Bump webpack from 5.70.0 to 5.76.0 in
/scripts/tools/bundle-...</li>
<li>Additional commits viewable in <a
href="https://github.com/prettier/prettier/compare/2.8.4...2.8.6">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=prettier&package-manager=npm_and_yarn&previous-version=2.8.4&new-version=2.8.6)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>